### ISSUE TITLE
Change Save Location

### ISSUE THREAD

**Issue by danielwgraf** [MySportsFeeds/mysportsfeeds-node#1]
Hey! This is very useful for a small project that I've been working on, but I'm trying to change the storeLocation. What's the best way to do this?

**Comment by cooperbrenneman** [comment]
@danielwgraf, you can change the store location using the below input parameters for the MySportsFeeds object:
```javascript
var msf = new MySportsFeeds("1.0", true, "file", "results/newfolder/");
```
