### ISSUE TITLE
Result is state pending

### ISSUE THREAD

**Issue by endyourif** [MySportsFeeds/mysportsfeeds-node#3]
I'm performing the following API call using the Node.js package:

```
var msf = new MySportsFeeds("1.2", true, null);
var today = new Date();

var data = msf.getData('nhl', '2017-2018-regular', 'scoreboard', 'json', { 
	fordate: today.getFullYear() + 
		('0' + parseInt(today.getMonth() + 1)).slice(-2) + 
		('0' + today.getDate()).slice(-2),
	force: true
});

console.log(data);
```

The results in data is { state: 'pending' }. I've removed the authenticate call from the example. When I don't specify null for the store to file, the data is saved successfully on disk.

Am I doing something wrong?

**Comment by phc284** [comment]
I am getting `{state: pending}' also. Have you found a fix for this?

**Comment by bradbarkhouse** [comment]
@endyourif @phc284 Oh, I think that's b/c it may be returning a promise, not the data itself.  We'll need to add that inside the getData() call ...

**Comment by phc284** [comment]
Just tested it out and it is returning a promise if the call is grabbing from the local file if data hasn't changed. @endyourif, the fix I just did, for now, is just resolving the promise and sending my data in the resolved block of code (ex. below).


``` 
    msf.getData('nfl', '2017-2018-regular','team_gamelogs', 'json', {team: 'min'})
    .then((result) => {
      //check to see if data is coming back correct
      console.log('result', result); 
      //send to client
      res.send(result)
    });
```

**Comment by endyourif** [comment]
Thanks this has resolved my issue.
